apiVersion: v1
kind: ConfigMap
metadata:
  name: my-web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Hello-World.exe</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                /* CSS-Regeln hier einbetten */
                * {
                    margin: 0;
                    padding: 0;
                }

                section { 
                    width: 100%; 
                    height: 100vh; 
                    color : #4d4d4d;
                    background: linear-gradient(-45deg, #453034, #A8AE95, #aa6934, #F8C067); 
                    background-size: 800% 800%; 
                    position: relative;
                    display: flex; 
                    justify-content: center; 
                    align-items: center; 
                    animation: change 5s ease-in-out infinite; 
                }

                .container {
                    display: inline-block;
                    position: absolute;
                }

                .text {
                    font-size: 7rem;
                    letter-spacing: 15px;
                    font-family: monospace;
                    border-right: 5px solid;
                    width: 100%;
                    white-space: nowrap;
                    overflow: hidden;
                    animation: 
                        typing 3s steps(15),
                        cursor .4s step-end infinite alternate;
                }

                .hello {
                    color: #4d4d4d;
                    font-weight: 100;
                }

                span {
                    color: #453034;
                    font-weight: bolder;
                }

                @keyframes cursor {
                    50% { border-color: transparent; }
                }

                @keyframes typing {
                    from { width: 0; }
                }

                @keyframes change { 
                    0% { background-position: 0 50%; }
                    50% { background-position: 100% 50%; }
                    100% { background-position: 0 50%; }
                }

                @media all and (max-width: 1165px) {
                    section { width: 100%; }
                    .text { font-size: 5rem; }
                }

                @media all and (max-width: 900px) {
                    section { width: 100%; }
                    .text { font-size: 4rem; }
                }

                @media all and (max-width: 767px) {
                    section { width: 100%; }
                    .text { font-size: 3rem; }
                }

                @media all and (max-width: 635px) {
                    section { width: 100%; }
                    .text { font-size: 2.5rem; }
                }

                @media all and (max-width: 569px) {
                    section { width: 100%; }
                    .text { font-size: 2rem; }
                }

                @media all and (max-width: 500px) {
                    section { width: 100%; }
                    .text { font-size: 1rem; }
                }
            </style>
        </head>
        
        <body>
            <section id="section">
                <div class="container">
                    <p class="text"><span class="hello">&lt;HELLO</span> <span>WORLD /&gt;</span></p>
                </div>
            </section>
        </body>
    </html>